"""Add permissions column and get_permissions to Role for Flask-Security-Too

Revision ID: 160a19a33cd5
Revises: 13c83c53107e
Create Date: 2025-07-07 20:29:23.974737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160a19a33cd5'
down_revision = '13c83c53107e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
