"""Add billing and pricing fields

Revision ID: 5fd0d47b93ca
Revises: dc024f26d6ba
Create Date: 2025-07-12 07:05:32.002171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd0d47b93ca'
down_revision = 'dc024f26d6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_discount_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('agent_discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('terms_conditions', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_billing_invoice_number', ['invoice_number'])
        batch_op.drop_column('amount')

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_base_discount', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.Date(), nullable=True))
        batch_op.alter_column('percent',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_discount_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('agent_discount_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_discount_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=128), nullable=True))
        batch_op.create_foreign_key('fk_job_service_id', 'service', ['service_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('base_price')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('final_price')
        batch_op.drop_column('additional_charges')
        batch_op.drop_column('additional_discount_percent')
        batch_op.drop_column('agent_discount_percent')
        batch_op.drop_column('base_discount_percent')
        batch_op.drop_column('base_price')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.alter_column('percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('valid_to')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_base_discount')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('amount')
        batch_op.drop_column('name')

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('terms_conditions')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('additional_charges')
        batch_op.drop_column('additional_discount_amount')
        batch_op.drop_column('agent_discount_amount')
        batch_op.drop_column('base_discount_amount')
        batch_op.drop_column('base_price')
        batch_op.drop_column('due_date')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_number')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('agent_discount_percent')

    # ### end Alembic commands ###
