from .role import Role
from .user import User
from .service import Service
from .vehicle import Vehicle
from .job import Job
from .driver import Driver
from .agent import Agent
from .billing import Billing
from .discount import Discount
from .association import roles_users
from .price import Price
from .customer_discount import CustomerDiscount 