from extensions import db

class Job(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    customer_name = db.Column(db.String(128))
    customer_email = db.Column(db.String(128))
    customer_mobile = db.Column(db.String(32))
    customer_reference = db.Column(db.String(128))
    passenger_name = db.Column(db.String(128))
    passenger_email = db.Column(db.String(128))
    passenger_mobile = db.Column(db.String(32))
    type_of_service = db.Column(db.String(128))
    pickup_date = db.Column(db.String(32))
    pickup_time = db.Column(db.String(32))
    pickup_location = db.Column(db.String(256))
    dropoff_location = db.Column(db.String(256))
    vehicle_type = db.Column(db.String(64))
    vehicle_number = db.Column(db.String(64))
    driver_contact = db.Column(db.String(128))
    payment_mode = db.Column(db.String(64))
    payment_status = db.Column(db.String(64))
    order_status = db.Column(db.String(64))
    message = db.Column(db.Text)
    remarks = db.Column(db.Text)
    has_additional_stop = db.Column(db.Boolean, default=False)
    additional_stops = db.Column(db.Text)
    has_request = db.Column(db.Boolean, default=False)
    reference = db.Column(db.String(128))
    status = db.Column(db.String(32), default='Inactive')
    date = db.Column(db.String(64))
    driver_id = db.Column(db.Integer, db.ForeignKey('driver.id'))
    agent_id = db.Column(db.Integer, db.ForeignKey('agent.id')) 